_target_: src.models.base_cnn.BaseCNN

in_channels: 3
out_channels: 180

hidden_channels: [64, 128, 256]
kernel_sizes: [3, 3, 3]
strides: [2, 2, 2]
padding: [1, 1, 1]

batchnorm: true

linear_hidden_features: [256, 128, 64]
linear_out_features: ${data.num_attributes}

final_tanh: false
