_target_: src.models.base_cnn.BaseCNN

in_channels: 12
out_channels: 64

hidden_channels: [64, 128]
kernel_sizes: [3, 3]
strides: [1, 1]

use_pooling: false
pool_kernel_size: 2
pool_stride: 1

linear_out_features: 1