_target_: src.models.base_cnn.BaseCNN

in_channels: 12
out_channels: 256

hidden_channels: [64, 64, 128, 256, 256]
kernel_sizes: [3, 3, 3, 3, 3]
strides: [1, 1, 1, 1, 1]
padding: [1, 1, 1, 1, 1]

linear_out_features: 1