device: cuda

num_epochs: 10
batch_size: 64

lr: 0.0001
loss_fn: CrossEntropyLoss

accuracy:
  enable: true
  per_attribute: true
  threshold: 0.5

save_checkpoint_every: 5
checkpoint_path: ${hydra:runtime.output_dir}/checkpoints
tensorboard_log_dir: ${hydra:runtime.output_dir}/logs
logs_per_epoch: 100
train_write_every: 10