device: cpu

num_epochs: 100
batch_size: 64

lr: 0.001
loss_fn: MSELoss

save_checkpoint_every: 20
checkpoint_path: ${hydra:runtime.output_dir}/checkpoints
tensorboard_log_dir: ${hydra:runtime.output_dir}/logs
logs_per_epoch: 100