device: cuda

num_epochs: 100
batch_size: 64

lr: 0.0001
loss_fn: BCEWithLogitsLoss

save_checkpoint_every: 20
checkpoint_path: ${hydra:runtime.output_dir}/checkpoints
tensorboard_log_dir: ${hydra:runtime.output_dir}/logs
logs_per_epoch: 100
train_write_every: 100
