device: cpu
seed: 42

num_epochs: 100
batch_size: 64

lr: 0.001
loss_fn: MSELoss

save_checkpoint_every: 20
checkpoint_path: ${hydra:runtime.cwd}/models/chess

tensorboard_log_dir: ${hydra:runtime.output_dir}/chess
logs_per_epoch: 100