defaults:
  - _self_

problem: chess
mode: base_cnn

train: ${problem}/train
data: ${problem}/data
model: ${problem}/models/${mode}

seed: 42

hydra:
  run:
    dir: ${hydra:runtime.cwd}/outputs/${problem}/${mode}/${now:%Y-%m-%d}/${now:%H-%M-%S}