defaults:
  - data: crc
  - train: default
  - model: gecnn
  - _self_

problem: crc
mode: gecnn
seed: 21

hydra:
  run:
    dir: ${hydra:runtime.cwd}/outputs/${problem}/${mode}/${now:%Y-%m-%d}/${now:%H-%M-%S}
