defaults:
  - _self_
  - train: ${problem}/train
  - data: ${problem}/data
  - model: ${problem}/models/base_cnn

hydra:
  run:
    dir: ${hydra:runtime.cwd}/outputs/chess/${now:%Y-%m-%d}/${now:%H-%M-%S}